"""tenant isolation (M6 Phase 1, resolves D3)

Adds the `tenants` table and a `tenant_id` FK to every tenant-scoped table
(users, jobs, candidates, resumes, applications, interviews). Written by hand,
not autogenerated: this is a populated-table NOT NULL backfill plus unique-
constraint surgery, exactly the kind of migration this project's own Runbook
warns autogenerate handles poorly.

Sequence per table: add tenant_id nullable -> backfill every existing row to
the one seed tenant (Northwind Health, matches the frontend's hardcoded org)
-> make it NOT NULL -> FK + index. `users.email` and `candidates.email` move
from globally UNIQUE to UNIQUE (tenant_id, email) — the constraint change D3
flagged as most expensive once real data exists; done now while there's only
one tenant.

`skills` / `resume_skills` / `job_skills` / `ai_processing_logs` are
deliberately NOT touched: skills is a shared taxonomy, not tenant data, and
the join tables inherit isolation transitively through their parent FKs.

Revision ID: c3d4e5f6a7b8
Revises: a1b2c3d4e5f6
Create Date: 2026-08-09 16:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c3d4e5f6a7b8'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Fixed, obviously-synthetic id so this migration and app/seed.py can agree on
# "the one seed tenant" without a lookup.
SEED_TENANT_ID = '11111111-1111-1111-1111-111111111111'

TENANT_SCOPED_TABLES = ['users', 'jobs', 'candidates', 'resumes', 'applications', 'interviews']


def upgrade() -> None:
    op.create_table(
        'tenants',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('slug', sa.String(length=100), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('slug'),
    )
    op.execute(
        f"INSERT INTO tenants (id, name, slug, created_at) "
        f"VALUES ('{SEED_TENANT_ID}', 'Northwind Health', 'northwind-health', now())"
    )

    for table in TENANT_SCOPED_TABLES:
        op.add_column(table, sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=True))
        op.execute(f"UPDATE {table} SET tenant_id = '{SEED_TENANT_ID}'")
        op.alter_column(table, 'tenant_id', nullable=False)
        op.create_foreign_key(
            f'fk_{table}_tenant_id', table, 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE'
        )
        op.create_index(f'idx_{table}_tenant', table, ['tenant_id'])

    # The constraint surgery D3 warned about: global-unique -> per-tenant-unique.
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_unique_constraint('uq_users_tenant_email', 'users', ['tenant_id', 'email'])

    op.drop_constraint('candidates_email_key', 'candidates', type_='unique')
    op.create_unique_constraint('uq_candidates_tenant_email', 'candidates', ['tenant_id', 'email'])


def downgrade() -> None:
    op.drop_constraint('uq_candidates_tenant_email', 'candidates', type_='unique')
    op.create_unique_constraint('candidates_email_key', 'candidates', ['email'])

    op.drop_constraint('uq_users_tenant_email', 'users', type_='unique')
    op.create_unique_constraint('users_email_key', 'users', ['email'])

    for table in TENANT_SCOPED_TABLES:
        op.drop_index(f'idx_{table}_tenant', table_name=table)
        op.drop_constraint(f'fk_{table}_tenant_id', table, type_='foreignkey')
        op.drop_column(table, 'tenant_id')

    op.drop_table('tenants')
